import Head from 'next/head'
import Image from 'next/image'
import {auth, db} from '../firebase'
import {useState, useContext, useEffect, Fragment} from 'react'
import styles from '../styles/Home.module.css'
import { collection, getDocs, doc, setDoc, addDoc, getDoc,getCountFromServer } from "firebase/firestore";
import { useRouter } from 'next/router'
import Link from 'next/link'
import {signOut, onAuthStateChanged} from 'firebase/auth'



export default function Home() {
  const router = useRouter()
  const [displayName, setDisplayName] = useState()
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [isTeacher, setIsTeacher] = useState(false)
  const [schoolName, setSchoolName] = useState("")
  const [modalIsOpen, setIsOpen] = useState(false);
  const [selectedOption, setSelectedOption] = useState(null);
  const [docData, setDocData] = useState(null);
  const [teacherRequestLength, setTeacherRequestLength] = useState(0);

  function openModal() {
    setIsOpen(true);
  }

  const fetchUser = () => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        setIsLoggedIn(true)
      
      const fetch = async() => {
        try{
            const docRef = doc(db, "users", user.uid);
            console.log({user})
            const docSnap = await getDoc(docRef);

            if (docSnap.exists()) {
              setDocData(docSnap.data())
              console.log("Document data:", docSnap.data());
              if (docSnap.data().role == "teacher") {
                setIsTeacher(true)
                const collectionRef = collection(db, 'schools', docSnap.data().school_abbreviated+"_"+docSnap.data().school_id, 'teacher_requests');
                const snapshot = await getCountFromServer(collectionRef);
                console.log("snapshot data", snapshot.data().count);
                setTeacherRequestLength(snapshot.data().count - 1)
              }
              
              setSchoolName(docSnap.data().school_name)
            } else {
              router.replace("/login")
              console.log("No such document!");
            }
            } catch (err){
              console.log(err)
            }
      }
      fetch()}
    });
    
    
}

  console.log(auth)
  useEffect(() => {
    fetchUser()
    setDisplayName(localStorage.getItem('displayName'))
    console.log(auth.lastNotifiedUid)
  }, [])

  const options = [
    { value: 'createNew', label: 'Create a new club...' },
  ];
useEffect(() => {
    console.log(selectedOption)
}, [selectedOption])
  return (
    <div className={styles.container}>
      <Head>
        <title>NewsFlash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>NewsFlash</a>
        </h1>

        <p className={styles.description}>
        {docData && <Fragment>{docData.school_name}</Fragment>}
        {!docData &&
          <Fragment>For School/Business Purposes</Fragment>
        }
          
        </p>
        {isLoggedIn &&
    <p>Hello <b>{displayName}</b> ({docData && <Fragment>{docData.role}{docData.waiting_approval && <Fragment> waiting for teacher approval</Fragment>}</Fragment> })</p>
      }
        

        <div className={styles.grid}>
        {!isLoggedIn &&
        <Link href="/login" className={styles.card}>
              <h2>Sign-In&rarr;</h2>
              <p>Login with your google account</p>
            </Link>
      }
          {isLoggedIn &&
            <Fragment>
          <Link href="/today" className={styles.card}>
            <h2>Morning Announcements &rarr;</h2>
            <p>{"Check out the today's morning announcements"}</p>
          </Link>

          <Link href="/calendar" className={styles.card}>
            <h2>Past Announcements &rarr;</h2>
            <p>{"Check out the past announcements"}</p>
          </Link>
          
            
            <div className={styles.card} onClick={(e) => {signOut(auth).then(function() {
            e.preventDefault()
            console.log('Signed Out');
            localStorage.removeItem("displayName")
            router.reload()
          }, function(error) {
            console.error('Sign Out Error', error);
          });}}>
            <h2>&larr; Log out </h2>
            <p>{"Log out of google account"}</p>
          </div>
          {
            isTeacher &&
            <Fragment>
            <Link href="/createAnnouncement" className={styles.card}>
          <h2>Create Announcement &rarr;</h2>
          <p>Create a new announcement in {schoolName}</p>
        </Link>
            <Link href="/teacherRequests" className={styles.card}>
          <h2>Teacher Requests &rarr;</h2>
          <p>You have <b>{teacherRequestLength}</b> teacher requests at the moment</p>
        </Link>
            </Fragment>
            
          }          
            </Fragment>
        }
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://github.com/D-Haran/"
          target="_blank"
          rel="noopener noreferrer"
        >Made by Derrick Ratnaharan
          <span className={styles.logo}>
            <Image src={"/static/github.png"} width={"20"} height={"20"} />
          </span>
        </Link>
      </footer>
    </div>
  )
}
